const MODULES = [
  {id:1, titulo:'Cosmovisão Africana e o Candomblé', carga:'3h', subtitulo:'História, nações, Orixás e ancestralidade', descricao:'Compreender o Candomblé como sistema religioso e civilizatório, marcado por ancestralidade, resistência cultural e produção de sentidos.', materiais:[['PDF do módulo','modulo1.pdf'],['Atividade prática','atividade1.pdf']], quiz:[
    {q:'O objetivo principal do módulo 1 é compreender o Candomblé como:', opts:['Folclore sem relação com saúde','Sistema religioso e civilizatório com lógica própria','Prática individual sem dimensão comunitária'], a:1, fb:'O curso reconhece o Candomblé como sistema religioso, cultural e comunitário, não como superstição.'},
    {q:'A noção de ancestralidade no Candomblé contribui para:', opts:['Apagar a história da diáspora africana','Fortalecer pertencimento, memória e resistência','Separar religião e vida cotidiana'], a:1, fb:'A ancestralidade sustenta vínculos, identidade, memória coletiva e pertencimento.'},
    {q:'Uma postura adequada do profissional do SUS diante desses saberes é:', opts:['Curiosidade respeitosa e humildade epistemológica','Julgamento das práticas religiosas','Silenciamento da experiência do usuário'], a:0, fb:'A escuta respeitosa é base para um cuidado integral e culturalmente sensível.'}
  ]},
  {id:2, titulo:'O Terreiro como Espaço de Cuidado', carga:'2h30', subtitulo:'Acolhimento, pertencimento e vínculo comunitário', descricao:'Reconhecer o terreiro como território social de cuidado, onde se produzem acolhimento, apoio comunitário e sentidos para o sofrimento.', materiais:[['PDF do módulo','modulo2.pdf'],['Atividade prática','atividade2.pdf']], quiz:[
    {q:'O terreiro pode ser compreendido como território de cuidado porque:', opts:['Substitui formalmente todos os serviços de saúde','Produz acolhimento, vínculo, pertencimento e apoio comunitário','Funciona apenas como espaço de festas'], a:1, fb:'O terreiro não substitui o SUS, mas pode compor itinerários de cuidado.'},
    {q:'A liderança religiosa no terreiro pode exercer papel de:', opts:['Escuta, orientação e referência comunitária','Autoridade biomédica obrigatória','Figura sem impacto na saúde mental'], a:0, fb:'Lideranças podem sustentar vínculos, orientações e acolhimento comunitário.'},
    {q:'Para o profissional, reconhecer o terreiro implica:', opts:['Valorizar redes de apoio do usuário','Proibir práticas religiosas','Ignorar o território do paciente'], a:0, fb:'O cuidado integral considera redes, vínculos, cultura e território.'}
  ]},
  {id:3, titulo:'Cosmologia do Cuidado no Candomblé', carga:'3h', subtitulo:'Saúde, doença, equilíbrio e ritual', descricao:'Compreender a lógica do processo saúde-doença-cuidado a partir da cosmologia religiosa, dos Orixás e da busca por equilíbrio.', materiais:[['PDF do módulo','modulo3.pdf'],['Atividade prática','atividade3.pdf']], quiz:[
    {q:'Na cosmologia do Candomblé, o adoecimento pode ser interpretado também como:', opts:['Desarmonia que exige cuidado e reorganização','Algo sem relação com corpo e comunidade','Prova de ausência de fé'], a:0, fb:'A compreensão religiosa pode atribuir sentido ao sofrimento e orientar práticas de cuidado.'},
    {q:'Os rituais, como banhos e ebós, são apresentados no curso como:', opts:['Substitutos automáticos da clínica','Práticas simbólicas que podem reorganizar sentidos e experiências','Condutas sem qualquer relevância subjetiva'], a:1, fb:'O curso propõe escuta e compreensão, sem substituir critérios técnicos do cuidado em saúde.'},
    {q:'Ao ouvir uma explicação espiritual sobre sofrimento, o profissional deve:', opts:['Patologizar imediatamente a fala','Acolher a narrativa e articulá-la ao projeto terapêutico','Interromper a conversa'], a:1, fb:'A escuta da narrativa do usuário fortalece vínculo e integralidade.'}
  ]},
  {id:4, titulo:'Corporeidade e Práticas de Cura', carga:'3h', subtitulo:'Corpo, ritual e experiência religiosa', descricao:'Refletir sobre o corpo como construção social e experiência vivida, superando a separação rígida entre corpo, mente, cultura e espiritualidade.', materiais:[['PDF do módulo','modulo4.pdf'],['Atividade prática','atividade4.pdf']], quiz:[
    {q:'A corporeidade ajuda a compreender que o cuidado envolve:', opts:['Somente o corpo biológico','Corpo, emoção, rito, cultura e vínculo','Apenas sintomas físicos mensuráveis'], a:1, fb:'O módulo amplia a compreensão do corpo para além do modelo biomédico restrito.'},
    {q:'Dança, toque, banho e rito podem atuar sobre:', opts:['A experiência corporal e subjetiva do adoecimento','Somente a estética da cerimônia','A negação do cuidado clínico'], a:0, fb:'Práticas corporais podem produzir sentido, pertencimento e reorganização da experiência.'},
    {q:'Superar o dualismo mente-corpo significa:', opts:['Separar espiritualidade de saúde','Compreender o sujeito de forma integral','Reduzir tudo ao psicológico'], a:1, fb:'A integralidade considera múltiplas dimensões do sujeito.'}
  ]},
  {id:5, titulo:'Racismo Religioso e Barreiras ao Cuidado', carga:'3h', subtitulo:'Direitos, laicidade e acesso ao SUS', descricao:'Discutir como o racismo religioso produz sofrimento, silenciamento, barreiras de acesso e desqualificação dos saberes de terreiro.', materiais:[['PDF do módulo','modulo5.pdf'],['Atividade prática','atividade5.pdf']], quiz:[
    {q:'O racismo religioso no campo da saúde pode aparecer como:', opts:['Apenas agressões físicas explícitas','Desqualificação, piadas, suspeita e patologização da fé','Um problema sem relação com atendimento'], a:1, fb:'O racismo religioso também atua de forma simbólica e institucional.'},
    {q:'Laicidade no serviço público significa:', opts:['Respeitar a diversidade religiosa sem privilegiar ou perseguir tradições','Proibir usuários de falar sobre religião','Aceitar apenas religiões majoritárias'], a:0, fb:'Laicidade não é apagamento da religião do usuário, mas garantia de respeito e igualdade.'},
    {q:'Uma prática profissional antirracista exige:', opts:['Escuta, reconhecimento das violências e compromisso com equidade','Neutralidade que ignora desigualdades','Evitar qualquer diálogo com povos de terreiro'], a:0, fb:'Equidade exige reconhecer desigualdades e atuar para reduzi-las.'}
  ]},
  {id:6, titulo:'Diálogos entre Terreiro e SUS', carga:'2h30', subtitulo:'Integralidade e escuta sensível', descricao:'Construir possibilidades de diálogo entre saberes tradicionais e técnico-científicos, com foco em integralidade, território e vínculo.', materiais:[['PDF do módulo','modulo6.pdf'],['Atividade prática','atividade6.pdf']], quiz:[
    {q:'Uma ponte possível entre SUS e terreiro é:', opts:['Roda de conversa com respeito, pactuação e reconhecimento territorial','Substituição do tratamento clínico por ritual','Interdição do tema religioso nos serviços'], a:0, fb:'Pontes são construídas com diálogo, pactuação e respeito aos territórios.'},
    {q:'Escuta sensível significa:', opts:['Concordar com tudo sem critério','Acolher a experiência do usuário sem julgamento','Evitar qualquer pergunta sobre espiritualidade'], a:1, fb:'Escutar não é abandonar técnica; é ampliar o cuidado.'},
    {q:'A integralidade na prática demanda:', opts:['Considerar dimensões biológicas, psicológicas, sociais, culturais e espirituais','Focar apenas na doença','Recusar saberes não biomédicos'], a:0, fb:'Integralidade considera o sujeito em sua complexidade.'}
  ]},
  {id:7, titulo:'Guia Prático: O que Fazer e o que Evitar', carga:'2h30', subtitulo:'Condutas, consulta e cuidado', descricao:'Oferecer orientações práticas para abordar religiosidade na consulta, evitando julgamento, piadas, patologização e silenciamento.', materiais:[['PDF do módulo','modulo7.pdf'],['Atividade prática','atividade7.pdf']], quiz:[
    {q:'Uma pergunta adequada na consulta seria:', opts:['Você vai abandonar isso para fazer tratamento?','Existe alguma prática ou rede de apoio importante para seu cuidado?','Seu terreiro causa seus sintomas?'], a:1, fb:'Perguntas abertas e respeitosas favorecem vínculo e autonomia.'},
    {q:'Uma atitude a evitar é:', opts:['Acolher a narrativa do usuário','Patologizar automaticamente a experiência religiosa','Perguntar com respeito'], a:1, fb:'Patologizar a fé pode gerar silenciamento e afastamento do cuidado.'},
    {q:'Usar a fé como recurso terapêutico significa:', opts:['Valorizar aquilo que fortalece o usuário sem impor crenças','Transformar o serviço em espaço religioso','Retirar a medicação'], a:0, fb:'A fé pode ser recurso de enfrentamento quando integrada com respeito e critério.'}
  ]},
  {id:8, titulo:'O que o SUS pode aprender com os terreiros?', carga:'2h30', subtitulo:'Vínculo, sentido e cuidado comunitário', descricao:'Sintetizar contribuições dos terreiros para um SUS mais humano, plural, equânime e integral.', materiais:[['PDF do módulo','modulo8.pdf'],['Atividade prática','atividade8.pdf']], quiz:[
    {q:'Entre as aprendizagens dos terreiros para o SUS está:', opts:['Acolhimento, pertencimento, vínculo e cuidado comunitário','Exclusão da espiritualidade do cuidado','Padronização rígida da experiência'], a:0, fb:'O terreiro ensina sobre vínculo, comunidade, escuta e sentido.'},
    {q:'O curso propõe que o SUS:', opts:['Substitua seus protocolos por rituais','Reconheça saberes tradicionais sem abandonar o cuidado técnico','Ignore territórios religiosos'], a:1, fb:'A proposta é diálogo, não substituição.'},
    {q:'A principal contribuição do percurso formativo é:', opts:['Construir pontes entre ciência, cultura, ancestralidade e cuidado','Separar saúde mental e espiritualidade','Transformar profissionais em sacerdotes'], a:0, fb:'Pontes de cuidado exigem respeito, escuta e integralidade.'}
  ]}
];

const PRE_TEST = [
 {q:'Na sua opinião, qual é a principal função de um terreiro de Candomblé para a comunidade?',opts:['Apenas um local de culto e rituais religiosos.','Um espaço de acolhimento e práticas de cuidado, com relevância para a saúde comunitária.','Um local onde se praticam superstições sem relação com a saúde.','Um espaço de lazer e eventos culturais.'],a:1,fb:'O terreiro também funciona como território de cuidado, acolhimento e pertencimento.'},
 {q:'Você acredita que a fé religiosa de um paciente pode influenciar seu processo de saúde e doença?',opts:['Não, a saúde é uma questão puramente biológica.','Sim, mas apenas de forma negativa.','Sim, a fé pode ser recurso importante de enfrentamento do sofrimento.','Não sei opinar.'],a:2,fb:'A fé pode produzir sentido, suporte e fortalecimento subjetivo.'},
 {q:'Como você se sente ao lidar com pacientes de crenças religiosas diferentes das suas, especialmente de matriz africana?',opts:['Muito preparado, tive formação específica.','Inseguro, nunca recebi formação para lidar com diversidade religiosa.','Respeito, mas evito tocar no assunto.','Não acho relevante.'],a:1,fb:'A questão identifica lacunas formativas comuns nos serviços de saúde.'},
 {q:'O que você entende por racismo religioso no contexto dos serviços de saúde?',opts:['É um termo exagerado.','São apenas atos explícitos de agressão.','É a desqualificação e preconceito contra religiões de matriz africana, criando barreiras e violência simbólica.','Refere-se apenas ao preconceito contra religiões evangélicas.'],a:2,fb:'O racismo religioso opera também por silenciamento, suspeita, desqualificação e patologização da fé.'},
 {q:'Se um paciente relata melhora após um ritual no terreiro, qual seria sua reação?',opts:['Ignoraria ou minimizaria a fala.','Alertaria sobre curandeirismo.','Escutaria com atenção e perguntaria como essa prática o ajudou.','Mudaria a prescrição médica com base no relato.'],a:2,fb:'A escuta ativa reconhece a experiência do usuário sem substituir critérios técnicos.'},
 {q:'Para você, o princípio da integralidade no SUS já contempla adequadamente a dimensão espiritual dos usuários?',opts:['Sim, na teoria e na prática.','Não, espiritualidade não é saúde.','Sim, na teoria, mas na prática serviços e profissionais nem sempre estão preparados.','Integralidade contempla apenas dimensão física e psicológica.'],a:2,fb:'Há distância entre o princípio da integralidade e a prática cotidiana.'},
 {q:'Você considera os terreiros como territórios de cuidado para a saúde mental?',opts:['Não, cuidado mental deve ser exclusivo dos serviços de saúde.','Sim, pois oferecem acolhimento, sentido para o sofrimento e apoio comunitário.','Talvez, mas isso atrapalha tratamento convencional.','Não sei o que significa territórios de cuidado.'],a:1,fb:'Os terreiros podem integrar itinerários terapêuticos e produzir cuidado comunitário.'}
];
const POST_TEST = [
 {q:'Como a cosmologia iorubá e os Orixás se relacionam com o processo de saúde e doença?',opts:['São apenas mitos sem relação com saúde.','Desequilíbrios ou cobranças espirituais podem ser interpretados como sinais de desarmonia, e rituais buscam restabelecer equilíbrio.','Apenas Obaluaiê está relacionado com saúde.','A relação é simbólica e irrelevante para saúde mental.'],a:1,fb:'Na cosmologia iorubá, Orixás são forças vitais e rituais podem reorganizar a experiência do adoecimento.'},
 {q:'Sobre itinerário terapêutico, qual é a importância de reconhecer o terreiro nesse percurso?',opts:['O único itinerário válido é o biomédico.','O terreiro compete com o SUS.','O terreiro pode ser nó estruturante onde o sujeito encontra acolhimento, sentido e apoio.','O terreiro importa apenas para questões sociais.'],a:2,fb:'Itinerários terapêuticos envolvem múltiplos recursos de cuidado.'},
 {q:'Como a corporeidade contribui para compreender práticas de cuidado nos terreiros?',opts:['Práticas como dança, banhos e toques atuam na experiência corporal, integrando biológico, psicológico e espiritual.','Não se aplica aos terreiros.','É apenas exercício físico.','É o oposto da espiritualidade.'],a:0,fb:'O corpo no terreiro comunica pertencimento, experiência, emoção e cuidado.'},
 {q:'A pesquisa aponta o racismo religioso como determinante social da saúde. Assinale a melhor descrição.',opts:['Fenômeno raro, resumido a insultos.','Estrutura que desqualifica saberes de terreiro, patologiza a fé e cria barreiras de acesso.','É igual ao racismo racial, sem especificidades.','Problema apenas jurídico, sem impacto na saúde.'],a:1,fb:'O racismo religioso atravessa instituições e pode produzir sofrimento, silenciamento e barreiras.'},
 {q:'Qual é a principal proposta do curso para a prática profissional?',opts:['Incorporar rituais como procedimentos oficiais do SUS.','Substituir tratamentos biomédicos por práticas religiosas.','Promover escuta ativa e respeitosa, construindo pontes entre saber tradicional e biomédico.','Impedir que pacientes falem de religião.'],a:2,fb:'O curso forma uma postura de respeito, escuta e integralidade.'},
 {q:'Sobre eficácia simbólica dos rituais, é correto afirmar que:',opts:['Comprova que rituais têm o mesmo efeito de medicamentos.','O rito pode nomear o sofrimento, prescrever ações e reorganizar a experiência do adoecido.','Não tem aplicação prática na clínica.','É uma forma de engano.'],a:1,fb:'A eficácia simbólica ajuda a compreender como sentidos compartilhados podem produzir alívio e reorganização subjetiva.'},
 {q:'Qual deve ser a postura do profissional ao saber que um paciente realizou ritual no terreiro?',opts:['Orientar abandono das práticas religiosas.','Apenas alertar sobre riscos.','Reconhecer como parte do itinerário terapêutico, valorizar autonomia e perguntar como o paciente percebeu seus efeitos.','Ignorar a informação.'],a:2,fb:'A postura ética é de escuta, respeito e articulação.'}
];
